/**
 * Diagnostic script: reads model.json + weights binary to extract
 * the Rescaling layer constants and verify what preprocessing the model expects.
 */
import { readFileSync } from 'fs';

const modelDir = 'public/model';
const modelJson = JSON.parse(readFileSync(`${modelDir}/model.json`, 'utf8'));
const binBuf = readFileSync(`${modelDir}/group1-shard1of1.bin`);

// --- 1. Show model metadata ---
console.log('=== Model Metadata ===');
console.log('Format:', modelJson.format);
console.log('Generated by TF:', modelJson.generatedBy);
console.log('Converted by:', modelJson.convertedBy);

// --- 2. Show input/output signature ---
const sig = modelJson.signature;
if (sig) {
  console.log('\n=== Signature ===');
  console.log('Inputs:', JSON.stringify(sig.inputs, null, 2));
  console.log('Outputs:', JSON.stringify(sig.outputs, null, 2));
}

// --- 3. Find rescaling-related nodes in the graph ---
const nodes = modelJson.modelTopology?.node || [];
console.log(`\n=== Graph: ${nodes.length} total nodes ===`);

const rescalingNodes = nodes.filter(n =>
  n.name.toLowerCase().includes('rescaling')
);
console.log(`\nRescaling nodes (${rescalingNodes.length}):`);
rescalingNodes.forEach(n => {
  console.log(`  ${n.op}: ${n.name}`);
  if (n.input) console.log(`    inputs: ${JSON.stringify(n.input)}`);
});

// --- 4. Extract rescaling constant values from the binary weights ---
const manifest = modelJson.weightsManifest?.[0];
if (manifest) {
  const weights = manifest.weights;
  console.log(`\n=== Weights Manifest: ${weights.length} entries ===`);

  // Calculate byte offsets for each weight
  let offset = 0;
  const dtypeSize = { float32: 4, int32: 4, bool: 1 };

  for (const w of weights) {
    const elemSize = dtypeSize[w.dtype] || 4;
    const numElems = w.shape.reduce((a, b) => a * b, 1) || 1; // scalar = 1
    const byteLen = numElems * elemSize;

    // Check if this is a rescaling constant
    if (w.name.toLowerCase().includes('rescaling') ||
        w.name.toLowerCase().includes('cast/x') ||
        w.name.toLowerCase().includes('cast_1/x')) {
      const view = new DataView(binBuf.buffer, binBuf.byteOffset + offset, byteLen);

      let values;
      if (w.dtype === 'float32') {
        values = [];
        for (let i = 0; i < numElems; i++) {
          values.push(view.getFloat32(i * 4, true)); // little-endian
        }
      } else if (w.dtype === 'int32') {
        values = [];
        for (let i = 0; i < numElems; i++) {
          values.push(view.getInt32(i * 4, true));
        }
      }
      console.log(`\n  ★ ${w.name}`);
      console.log(`    shape: [${w.shape}], dtype: ${w.dtype}`);
      console.log(`    offset: ${offset}, bytes: ${byteLen}`);
      console.log(`    value(s):`, values);
    }

    offset += byteLen;
  }

  console.log(`\nTotal weight bytes: ${offset} (file: ${binBuf.length})`);
}

// --- 5. Find the input node and trace the first few operations ---
console.log('\n=== Input → First Ops Chain ===');
const inputNode = nodes.find(n => n.op === 'Placeholder');
if (inputNode) {
  console.log(`Input: ${inputNode.name} (${inputNode.op})`);
  console.log(`  shape:`, JSON.stringify(inputNode.attr?.shape));

  // Trace what uses the input
  const usersOfInput = nodes.filter(n => n.input?.includes(inputNode.name));
  usersOfInput.forEach(n => {
    console.log(`  → ${n.name} (${n.op})`);
    const usersOf2 = nodes.filter(n2 => n2.input?.includes(n.name));
    usersOf2.forEach(n2 => {
      console.log(`    → ${n2.name} (${n2.op})`);
    });
  });
}

// --- 6. Find the output node and trace backwards ---
console.log('\n=== Output Chain ===');
const identityNode = nodes.find(n => n.name === 'Identity');
if (identityNode) {
  console.log(`Output: ${identityNode.name}, input: ${identityNode.input}`);
  // Trace back 3 levels
  let current = identityNode;
  for (let i = 0; i < 4; i++) {
    const inputName = current.input?.[0];
    if (!inputName) break;
    const prev = nodes.find(n => n.name === inputName);
    if (!prev) { console.log(`  ← (not found: ${inputName})`); break; }
    console.log(`  ← ${prev.name} (${prev.op})`);
    current = prev;
  }
}
